api:
  id: "19355702"

email-sapi:
  host: "email-sapi-a0y7fb.5sc6y6-3.usa-e2.cloudhub.io"
  base-path: "api"
  request_path: "mail"
  client_id: "66dc686f1a9449899a87d85c786377ed"
  client_secret: "83bc70194E2646578555c4319ce361D3"

sms-sapi:
  host: "sms-sapi-a0y7fb.5sc6y6-3.usa-e2.cloudhub.io"
  base-path: "api"
  request_path: "sms"
  client_id: "9d3501a1039c4cc6a549889cdca4a65d"
  client_secret: "aDf3528D48594F52aF079036668Bec28"